### ISSUE TITLE
Compile issue in new sdk changes

### ISSUE THREAD

**Issue by abhiint16** [estmob/SendAnywhere-Android-SDK#13]
I changed the code in the build.gradle

`implementation('com.estmob.android:sendanywhere:6.10.21@aar') {
        transitive = true
    }`

to `implementation('com.estmob.android:sendanywhere:10.12.3@aar') {
        transitive = true
    }`

Now I'm getting compile-time issue. See the error that I'm getting,

`Could not determine the dependencies of task ':app:compileDevDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:devDebugCompileClasspath'.
   > Could not find com.estmob.android:sendanywhere:10.12.3.
     Searched in the following locations:
         file:/Users/abhishekkumar/Library/Android/sdk/extras/m2repository/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.pom
         file:/Users/abhishekkumar/Library/Android/sdk/extras/m2repository/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.aar
         file:/Users/abhishekkumar/Library/Android/sdk/extras/google/m2repository/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.pom
         file:/Users/abhishekkumar/Library/Android/sdk/extras/google/m2repository/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.aar
         file:/Users/abhishekkumar/Library/Android/sdk/extras/android/m2repository/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.pom
         file:/Users/abhishekkumar/Library/Android/sdk/extras/android/m2repository/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.aar
         https://dl.google.com/dl/android/maven2/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.pom
         https://dl.google.com/dl/android/maven2/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.aar
         https://jcenter.bintray.com/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.pom
         https://jcenter.bintray.com/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.aar
         https://dl.bintray.com/ijabz/maven/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.pom
         https://dl.bintray.com/ijabz/maven/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.aar
         file:/Users/abhishekkumar/Desktop/The-Music-Player/app/libs/sendanywhere-10.12.3.aar
         file:/Users/abhishekkumar/Desktop/The-Music-Player/app/libs/sendanywhere.aar
         https://repo.maven.apache.org/maven2/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.pom
         https://repo.maven.apache.org/maven2/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.aar
         https://maven.fabric.io/public/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.pom
         https://maven.fabric.io/public/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.aar
         https://jitpack.io/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.pom
         https://jitpack.io/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.aar
         https://maven.google.com/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.pom
         https://maven.google.com/com/estmob/android/sendanywhere/10.12.3/sendanywhere-10.12.3.aar
     Required by:
         project :app
`

Kindly help.

**Comment by kyujin-sah** [comment]
the part where the problem may occur in the SDK has been fixed.
Try version 11.1.21 and let me know if compilation fails.

**Comment by abhiint16** [comment]
**After many attempts, we're still getting compilation issues.**

- I tried multiple times from our side just to see in case I'm doing any mistake. 
- Went through the commits of this SDK and found that recently classpath and gradle version of the SDK has been updated to `classpath 'com.android.tools.build:gradle:4.1.1' `  and `distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip` respectively.
- Was not sure about this but just to not miss any possible stuff from my side, I too updated these in the project here. Project synced well and again, once I build the project, got the following error message (this time the message is different):

`Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.estmob.android:sendanywhere:11.1.21.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/estmob/android/sendanywhere/11.1.21/sendanywhere-11.1.21.pom
       - https://jcenter.bintray.com/com/estmob/android/sendanywhere/11.1.21/sendanywhere-11.1.21.pom
     Required by:
         project :app`

- After searching a lot, I have found [this StackOverflow](https://stackoverflow.com/questions/64945616/android-execution-failed-for-task-checkdebugaarmetadata-a-failure-occurred-w) which somewhat looks similar to our issue here and it says that there might be some problem with gradle-6+ and pom files. Do look into it.
- After this, I cloned this project to see into it. After looking into different areas, what I found that in the project you guys are using `'com.estmob.android:sendanywhere-core:11.1.21@aar'` as a dependency (**see those -core at the last**) and cloned project compiles and builds successfully. Although it directly contains the files in a separate module in the project itself, hence there it might have worked. Hence when I used the same dependency in app-module, project compiled and built successfuly but the RecieveTask, SendTask, etc files are not accessible now. Even tried using this dependency in my project, even there it's the same issue. Now the questions remains: is the dependency `'com.estmob.android:sendanywhere:11.1.21@aar'`  or `'com.estmob.android:sendanywhere-core:11.1.21@aar'`.
- In both the cases, there are issues.

**Comment by abhiint16** [comment]
You can also look at this link for more reference in case it helps in any way:

[Link 1](https://github.com/transistorsoft/react-native-background-geolocation/issues/1077)

**Comment by kyujin-sah** [comment]
Sorry.
sendanywhere SDK 11.1.21 did not upload properly, so I uploaded again.

You can use the SDK in two ways.
1. using sendanywhere
implementation ('com.estmob.android:sendanywhere:11.1.21@aar') {
	transitive = true
}

2. using sendanywhere-core
implementation ('com.estmob.android:sendanywhere-core:11.1.21@aar') {
	transitive = true
}

If you use sendanywhere-core instead of sendanywhere, you must include the source code of RecieveTask and SendTask.

**Comment by kyujin-sah** [comment]
Sorry.

sendanywhere SDK 11.1.21 did not upload properly and there was a problem
with the pom file.
I uploaded sendanywhere SDK 11.1.21 again.

You can use the SDK in two ways.

   1.

   using sendanywhere
   implementation ('com.estmob.android:sendanywhere:11.1.21@aar') {
   transitive = true
   }
   2.

   using sendanywhere-core
   implementation ('com.estmob.android:sendanywhere-core:11.1.21@aar') {
   transitive = true
   }

If you use sendanywhere-core instead of sendanywhere, the source code of
RecieveTask and SendTask should be included in the project.



2021년 1월 21일 (목) 오후 5:50, Abhishek Kumar <notifications@github.com>님이 작성:
